# Generated by Django 3.2.4 on 2022-05-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
